<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Operator;
use Faker\Factory as Faker;

class OperatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $faker = Faker::create();
        $operators = [
                [
                    'user_id' => 1,
                    'name' => 'Federico Rossi',
                    'engagement_price' => 80.00,
                    'description' => 'Pianista classico con una passione per le composizioni contemporanee.',
                    'phone' => '111-222-3333',
                    "filename" => "cantante-1.jpeg",
                    "original_name" => "cantante-1.jpeg",
                    "file_path" => "uploads/cantante-1.jpeg",
                    'address' => 'Via Quercia 789',
                    'foundation_year' => 2013,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 2,
                    'name' => 'Armando Lentisco',
                    'engagement_price' => 60.00,
                    'description' => 'Violoncellista esperto con un repertorio che spazia dal classico al pop.',
                    'phone' => '444-555-6666',
                    "filename" => "cantante-2.jpeg",
                    "original_name" => "cantante-2.jpeg",
                    "file_path" => "uploads/cantante-2.jpeg",
                    'address' => 'Via Frassino 456',
                    'foundation_year' => 2016,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 3,
                    'name' => 'Luca Moretti',
                    'engagement_price' => 70.00,
                    'description' => 'Chitarrista poliedrico con una predilezione per la musica latina.',
                    'phone' => '777-888-9999',
                    "filename" => "cantante-3.jpeg",
                    "original_name" => "cantante-3.jpeg",
                    "file_path" => "uploads/cantante-3.jpeg",
                    'address' => 'Via Abete 234',
                    'foundation_year' => 2010,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 4,
                    'name' => 'Martina Ferrari',
                    'engagement_price' => 75.00,
                    'description' => 'Violinista eclettica che unisce tradizione e sperimentazione.',
                    'phone' => '123-987-6543',
                    "filename" => "cantante-4.jpeg",
                    "original_name" => "cantante-4.jpeg",
                    "file_path" => "uploads/cantante-4.jpeg",
                    'address' => 'Via Cedro 567',
                    'foundation_year' => 2014,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 5,
                    'name' => 'Nicola De Santis',
                    'engagement_price' => 55.00,
                    'description' => 'Sassofonista appassionato di jazz moderno e improvvisazione libera.',
                    'phone' => '876-543-2109',
                    "filename" => "cantante-5.jpeg",
                    "original_name" => "cantante-5.jpeg",
                    "file_path" => "uploads/cantante-5.jpeg",
                    'address' => 'Via Pino 789',
                    'foundation_year' => 2017,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 6,
                    'name' => 'Bob Marley',
                    'engagement_price' => 70.00,
                    'description' => 'Chitarrista appassionato con esperienza in rock e blues.',
                    'phone' => '123-456-7890',
                    "filename" => "cantante-6.jpeg",
                    "original_name" => "cantante-6.jpeg",
                    "file_path" => "uploads/cantante-6.jpeg",
                    'address' => 'Via Acero 789',
                    'foundation_year' => 2012,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 7,
                    'name' => 'Francesco BuonAnimo',
                    'engagement_price' => 75.00,
                    'description' => 'Violinista addestrato classicamente, eccellente nelle performance orchestrali.',
                    'phone' => '456-789-0123',
                    "filename" => "cantante-7.jpeg",
                    "original_name" => "cantante-7.jpeg",
                    "file_path" => "uploads/cantante-7.jpeg",
                    'address' => 'Via Olmo 321',
                    'foundation_year' => 2011,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 8,
                    'name' => 'Davide Salerno',
                    'engagement_price' => 65.00,
                    'description' => 'Sassofonista versatile esperto in jazz, funk e R&B.',
                    'phone' => '789-012-3456',
                    "filename" => "cantante-8.jpeg",
                    "original_name" => "cantante-8.jpeg",
                    "file_path" => "uploads/cantante-8.jpeg",
                    'address' => 'Via Betulla 567',
                    'foundation_year' => 2014,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 9,
                    'name' => 'Eva Francellini',
                    'engagement_price' => 55.00,
                    'description' => 'Pianista talentuosa focalizzata su jazz e stili contemporanei.',
                    'phone' => '555-555-5555',
                    "filename" => "cantante-9.jpeg",
                    "original_name" => "cantante-9.jpeg",
                    "file_path" => "uploads/cantante-9.jpeg",
                    'address' => 'Via Pino 123',
                    'foundation_year' => 2015,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 10,
                    'name' => 'Giulia Cavalieri',
                    'engagement_price' => 190.00,
                    'description' => 'Cantautrice e ballerina,vincitrice di amici e di Sanremo.',
                    'phone' => '555-555-5555',
                    "filename" => "cantante-10.jpeg",
                    "original_name" => "cantante-10.jpeg",
                    "file_path" => "uploads/cantante-10.jpeg",
                    'address' => 'Via delle scuderie 123',
                    'foundation_year' => 2001,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 11,
                    'name' => 'Olivia Romano',
                    'engagement_price' => 65.00,
                    'description' => 'Flautista con una predilezione per la musica barocca e le sonorità eteree.',
                    'phone' => '234-567-8901',
                    "filename" => "cantante-11.jpeg",
                    "original_name" => "cantante-11.jpeg",
                    "file_path" => "uploads/cantante-11.jpeg",
                    'address' => 'Via Castagno 123',
                    'foundation_year' => 2018,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 12,
                    'name' => 'Paola Esposito',
                    'engagement_price' => 75.00,
                    'description' => 'Trombettista virtuosa con una passione per il jazz e le improvvisazioni energetiche.',
                    'phone' => '345-678-9012',
                    "filename" => "cantante-12.jpeg",
                    "original_name" => "cantante-12.jpeg",
                    "file_path" => "uploads/cantante-12.jpeg",
                    'address' => 'Via Faggio 456',
                    'foundation_year' => 2015,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 13,
                    'name' => 'Quirino Martini',
                    'engagement_price' => 70.00,
                    'description' => 'Contrabbassista che spazia dal jazz al folk, con un tocco distintivo.',
                    'phone' => '567-890-1234',
                    "filename" => "cantante-13.jpeg",
                    "original_name" => "cantante-13.jpeg",
                    "file_path" => "uploads/cantante-13.jpeg",
                    'address' => 'Via Salice 789',
                    'foundation_year' => 2013,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 14,
                    'name' => 'Rosa Marchetti',
                    'engagement_price' => 60.00,
                    'description' => 'Violinista appassionata di musica da camera, con un repertorio diversificato.',
                    'phone' => '789-012-3456',
                    "filename" => "cantante-14.jpeg",
                    "original_name" => "cantante-14.jpeg",
                    "file_path" => "uploads/cantante-14.jpeg",
                    'address' => 'Via Tiglio 234',
                    'foundation_year' => 2016,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 15,
                    'name' => 'Salvatore Ricci',
                    'engagement_price' => 55.00,
                    'description' => 'Chitarrista acustico con un approccio contemporaneo e influenze folk.',
                    'phone' => '901-234-5678',
                    "filename" => "cantante-15.jpeg",
                    "original_name" => "cantante-15.jpeg",
                    "file_path" => "uploads/cantante-15.jpeg",
                    'address' => 'Via Rovere 567',
                    'foundation_year' => 2014,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 16,
                    'name' => 'Teresa Morelli',
                    'engagement_price' => 80.00,
                    'description' => 'Pianista virtuosa, esperta in repertori classici e contemporanei.',
                    'phone' => '123-456-7890',
                    "filename" => "cantante-16.jpeg",
                    "original_name" => "cantante-16.jpeg",
                    "file_path" => "uploads/cantante-16.jpeg",
                    'address' => 'Via Abete 789',
                    'foundation_year' => 2011,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 17,
                    'name' => 'Umberto Rossi',
                    'engagement_price' => 65.00,
                    'description' => 'Trombonista appassionato di musica latina e fusion jazz.',
                    'phone' => '456-789-0123',
                    "filename" => "cantante-17.jpeg",
                    "original_name" => "cantante-17.jpeg",
                    "file_path" => "uploads/cantante-17.jpeg",
                    'address' => 'Via Ontano 123',
                    'foundation_year' => 2017,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 18,
                    'name' => 'Valentina de lellis',
                    'engagement_price' => 70.00,
                    'description' => 'Violoncellista con un interesse speciale per la musica contemporanea sperimentale.',
                    'phone' => '789-012-3456',
                    "filename" => "cantante-18.jpeg",
                    "original_name" => "cantante-18.jpeg",
                    "file_path" => "uploads/cantante-18.jpeg",
                    'address' => 'Via Pino 456',
                    'foundation_year' => 2012,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 19,
                    'name' => 'Walter White',
                    'engagement_price' => 75.00,
                    'description' => 'Tastierista esperto con una passione per la musica progressiva e il rock sinfonico.',
                    'phone' => '234-567-8901',
                    "filename" => "cantante-19.jpeg",
                    "original_name" => "cantante-19.jpeg",
                    "file_path" => "uploads/cantante-19.jpeg",
                    'address' => 'Via Tiglio 789',
                    'foundation_year' => 2014,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'user_id' => 20,
                    'name' => 'Nello Taver',
                    'engagement_price' => 55.00,
                    'description' => 'Nello Taver, nome d arte di Vincenzo Siciliano, è uno dei creator di YouTube e Twitch più apprezzati in Italia',
                    'phone' => '901-234-5678',
                    "filename" => "cantante-20.jpeg",
                    "original_name" => "cantante-20.jpeg",
                    "file_path" => "uploads/cantante-20.jpeg",
                    'address' => 'Via Quercia 234',
                    'foundation_year' => 2016,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ];

            foreach ($operators as $operator) {
                $newoperator= new Operator;
                $newoperator->user_id = $operator['user_id'];
                $newoperator->name = $operator['name'];
                $newoperator->engagement_price = $operator['engagement_price'];
                $newoperator->description = $operator['description'];
                $newoperator->phone = $operator['phone'];
                $newoperator->filename = $operator["filename"];
                $newoperator->original_name = $operator["original_name"];
                $newoperator->file_path = $operator["file_path"];
                $newoperator->address = $operator['address'];
                $newoperator->foundation_year = $faker->dateTimeBetween('-50 years', 'now')->format('Y-m-d');

            
                $newoperator->save();
            }
            
    }
    }
